### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by CWSites** [koslib/helm-eks-action#12] opened 2021-04-15 13:57 UTC
I'm getting the following errors when attempting to build with 

```bash
  Collecting PyYAML<5.5,>=3.10
    Downloading PyYAML-5.4.1.tar.gz (175 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nu9ttkz2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython
         cwd: None
    Complete output (352 lines):
    Collecting setuptools
      Downloading setuptools-56.0.0-py3-none-any.whl (784 kB)
    Collecting wheel
      Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
    Collecting Cython
      Downloading Cython-0.29.23.tar.gz (2.1 MB)
    Using legacy setup.py install for Cython, since package 'wheel' is not installed.
    Installing collected packages: setuptools, wheel, Cython
        Running setup.py install for Cython: started
        Running setup.py install for Cython: finished with status 'error'
        ERROR: Command errored out with exit status 1:
         command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-od35nbso/Cython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-od35nbso/Cython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-f4maul3s/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-nu9ttkz2/overlay --compile --install-headers /tmp/pip-build-env-nu9ttkz2/overlay/include/python3.8/Cython
```

I think it may be related to https://github.com/kciter/aws-ecr-action/issues/20

**Comment by koslib** [comment] 2021-04-15 13:59
Hello @CWSites, this was actually resolved (and this is a duplicate of #9). Have you tried using the latest version of the module? If the issue persists, please send me your workflow manifest to inspect.

**Comment by CWSites** [comment] 2021-04-15 14:01
Ah thank you, I'll take a look!

**Comment by koslib** [comment] 2021-04-15 14:05
Feel free to re-open this issue if the problem persists for you.

**Closed by koslib** 2021-04-15 14:05 UTC
Labels: duplicate
