### ISSUE TITLE
Unable to connect to K8s cluster due to mismatch in client authentication api version

### ISSUE THREAD

**Issue by jimvmathews** [koslib/helm-eks-action#37] opened 2022-09-23 14:03 UTC
Unable to connect to K8s cluster due to mismatch in client authentication api version

Error:
Error: Kubernetes cluster unreachable: Get "https://5a51c73d67a28d21c8038197f2d67054.sk1.us-west-1.eks.amazonaws.com/version": getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/v1alpha1

**Comment by koslib** [comment] 2022-09-23 16:50
Hello @jimvmathews, thanks for reporting! What's your cluster version?

**Comment by koslib** [comment] 2022-10-16 17:00
Hey @jimvmathews, you can give it another shot now. I've updated the awscli and kubectl versions - could you let me know if it feels better now? Thanks!

**Comment by brunoflegler** [comment] 2022-10-17 15:00
Good morning @koslib, I had the same problem now, do I need to change something first?

**Comment by koslib** [comment] 2022-10-17 15:02
Hey @brunoflegler what's your cluster version? The only think I can imagine is kubectl being on a version not compatible with your cluster version, so let's start from there and we can gradually drill down to it.

**Comment by koslib** [comment] 2022-10-17 17:59
@brunoflegler can you try with action version `v1.25.2` and let me know if it worked? It feels like the kubectl version upgrade that happened in `v1.25.3` and onwards is what's blocking you folks. 

```
- uses: koslib/helm-eks-action:v1.25.2
....
```

**Comment by brunoflegler** [comment] 2022-10-18 14:32
Hi @koslib , I did the test yesterday and yes it works fixing the mentioned version.

**Comment by koslib** [comment] 2022-10-19 21:15
Thanks @brunoflegler for getting back to me on that! To be honest I don't see any other option other than sticking with version `v1.25.2` which is the last to support your k8s version.

How do you recommend this is handled? Because the action needs to be updated with fresh dependency versions, however I understand that some users might need to use older versions still. Would it make sense potentially to have branches based on k8s versions as well as relevant tagging? Any other ideas? 

At least I'm glad this is no longer an ongoing issue for you, even with this workaround stuff is working on your end:)

**Comment by koslib** [comment] 2022-10-22 18:06
Seems to be duplicate of #41 - closing this one and continuing discussion there

**Closed by koslib** 2022-10-22 18:06 UTC
Labels: bug, duplicate
